### PR TITLE
Very basic HTML templating for exports.

### PR DESCRIPTION
**Pull request by KevBelisle**
1. I moved the displayHtml() method into a BaseExportController class.
2. I changed the exportControllers in the menus into singletons.
3. The displayHtml() method now checks for a template file before using the default template.

The "templating" is very, *very* basic. It replaces the string "%%CONTENT%%" in the template with the data.

If you approve these changes, the next step would likely be to include a templating engine (maybe freemarker?), have the exportControllers give displayHtml() a model instead of a string, and include default templates as resources.

### CODE REVIEW

**Comment by kingargyle** [comment]
@KevBelisle have you thought about using freeMarker for the templating engine instead of reconstructing our own?

http://freemarker.org/

**Comment by KevBelisle** [comment]
@kingargyle : I actually mentioned the possibility of using freemarker in my comment ;)

The simple solution I implemented was very quick since it reuses the data-to-html-table conversion that was used previously.

I wanted to know what @Killerardvark's thoughts were first, since moving to a more in depth templating engine like freemarker might require adding in viewmodels as an intermediary step between the data and the template.

Personally, I'm all for going with freemarker, and if we decide to go with it, I suggest NOT merging this pull request. I'll submit a new pull request with freemarker templates.

**Comment by Killerardvark** [comment]
My only concern is compatibility. I want exports to be simple for the average user. If you can stick to that, feel free to make updates to the export sections.

**Comment by Killerardvark** [comment]
Let me know if you plan on making additions or changes, otherwise I'll merge everything in.

**Comment by kingargyle** [comment]
Maybe have an advance template implementation that can be enabled through a preference section?  This way the basic stays as the default, and if somebody needs or wants the advanced section they have to enable it specifically themselves.

**Comment by KevBelisle** [comment]
@Killerardvark : I plan on adding in freemarker templating. I should hopefully have a pull request with that next week.

I'll close this pull request and create an issue for further discussion.

**Pull request closed without merging**
