### PR TITLE
Player List Searching

### PR DESCRIPTION
**Pull request by CoreyAFraser**
My FLGS was chatting about wanting a feature like this, so I said I would look into it.
With long lists of players in the Registration screen, it can sometimes be hard to find players who were previously entered when a small change (faction) needs to be made.

searchPlayerList - Add filtering for lists of players to make it easier to edit players and find them when adding them to an event - Corey Fraser

### CODE REVIEW

**Comment by Killerardvark** [comment]
Thanks for the addition. I appreciate it. I do have to make some changes to it. 

Not every TO enters first and last name. Also, I've seen names with more than one space. This means where you split the name by space ad do a check on startsWith can cause an error or not find certain results. I'll be changing it to a simple contains method.

I've been working on those sections to make them easier to use. I'll be merging my changes in with yours and hopefully we'll have something easier to use. Thanks!

**Comment by Killerardvark** [comment]
Ah, I see what you were going for. You wanted the "startsWith" first. Just needs some checking to avoid errors.

**Comment by Killerardvark** [comment]
DoubleList should is meant to be generic hence the reason of using T for the type being used. Using the standard object toString should be used for filtering. Conveniently Player's toString method returns getName.

**Comment by CoreyAFraser** [comment]
@Killerardvark Thanks for the input, I didn't notice that the Player toString method returned the name, I probably should have looked a bit closer.
Also I should have probably done the check for when TOs don't enter a first and last name with a space between them.

I'm planning on taking a look through the list of issues to see if there is anywhere else I can help.

**Pull request merged**
