### PR TITLE
comments + select player 2 from random group

### PR DESCRIPTION
**Pull request by qanar**

### CODE REVIEW

**Comment by Killerardvark** [comment]
Thanks for adding the comments. I'll merge this in and give it some testing tonight. It looks solid though.

Also, I wonder if it's worth adding a check/retry condition to it. The function runs extremely fast even with 200+ players. Due to the random nature, i think it might be prudent to retry in the event of an outlier run that creates a bad pairing.

Think of Apple's shuffle function on their ipods. It's not true random because people complained about songs playing twice in a row or the same band playing too many times in a row. People often mistake "random" with "evenly distributed". So apple created a psuedo random function that checks for certain undesirable random outcomes and retries them.

**Comment by qanar** [comment]
As a TO I only used the program for up to 20/30 people. I understand what
you mean with true randomness, but feel that if we don't get conflicts
(unless unsolvable (6 out of 10 players from one team) it does not really
matter. After all, all pairings after round one should not bother with the
'groupId'. As long as it's correct and fast enough (even 1 or 2 seconds
doesn't matter imho) I would not worry about it.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Killerardvark** [comment]
New build is out with your changes. Give it a shot and let me know what you think. And thanks for the contribution!

**Comment by qanar** [comment]
Let me know if you need me to look at any other small issues

**Pull request merged**
